version: '{build}'
image: Visual Studio 2017
clone_depth: 10

environment:
  global:
      JULIA_VERSION: 1.1.1
  matrix:
    - VIM_VERSION: v8.0.0018
    - VIM_VERSION: v8.1.0000
    - VIM_VERSION: master
    - VIM_VERSION: nvim-v0.3.0
    - VIM_VERSION: nvim-vlatest

install:
  - ps: scripts\appveyor\install-vim.ps1
  - 'choco install julia --version %JULIA_VERSION%'
  - 'refreshenv'
  - 'git -c advice.detachedHead=false clone https://github.com/thinca/vim-themis --branch v1.5.4 --single-branch --depth 1 %TEMP%\vim-themis'

build: off

test_script:
  - 'julia --version'
  - '%THEMIS_VIM% --version'
  - '%TEMP%\vim-themis\bin\themis.bat --reporter dot'

deploy: off
